services:
  loki:
    build: ./monitoring/loki
    container_name: loki
    ports:
      - "9091:9091"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - spring-network

  prometheus:
    build: ./monitoring/prometheus
    ports:
      - "9090:9090"
    networks:
      - spring-network
    restart: always

  grafana:
    build: ./monitoring/grafana
    networks:
      - spring-network
    ports:
      - "9092:3000"
    restart: always

networks:
  spring-network:
    driver: bridge

